# Generated by Django 5.2.4 on 2025-08-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='descripcion',
            field=models.CharField(default='sin descripcion', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alimento',
            name='unidad',
            field=models.CharField(max_length=30),
        ),
    ]
