# Generated by Django 5.2.4 on 2025-07-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inicial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=50)),
                ('alimentacion', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Animales',
        ),
    ]
